---
- name: deploy the CS image software stack
  hosts: localhost
  connection: local
  user: ubuntu
  become: true

  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: import the atom apt key
      apt_key:
         id: 0A0FAB860D48560332EFB581B75442BBDE9E3B09
         url: https://packagecloud.io/AtomEditor/atom/gpgkey
         state: present

    - name: install atom repository
      apt_repository:
        repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
        state: present
        update_cache=yes

    - name: import the Google Chrome apt key
      apt_key:
         id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
         url: https://dl-ssl.google.com/linux/linux_signing_key.pub
         state: present

    - name: install Google Chrome repository
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        update_cache=yes

    - name: import the Slack apt key
      apt_key:
         id: DB085A08CA13B8ACB917E0F6D938EC0D038651BD
         url: https://packagecloud.io/slacktechnologies/slack/gpgkey
         state: present

    - name: install Slack repository
      apt_repository:
        repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        state: present
        update_cache=yes

    - name: import the sublime-text apt key
      apt_key:
         id: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
         url: https://download.sublimetext.com/sublimehq-pub.gpg
         state: present

    - name: install sublime-text repository
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable
        state: present
        update_cache=yes

    - name: import the vscode apt key
      apt_key:
         id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
         url: https://packages.microsoft.com/keys/microsoft.asc
         state: present

    - name: install vscode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        update_cache=yes

    - name: import the bazel apt key
      apt_key:
         id: 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
         url: https://bazel.build/bazel-release.pub.gpg
         state: present

    - name: install bazel repository
      apt_repository:
        repo: deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8
        state: present
        update_cache=yes

    - name: import the crystal apt key
      apt_key:
         id: 5995C83CD754BE448164192909617FD37CC06B54
         url: https://keybase.io/crystal/pgp_keys.asc
         state: present

    - name: install crystal repository
      apt_repository:
        repo: deb https://dist.crystal-lang.org/apt crystal main
        state: present
        update_cache=yes

    - name: import the NeuroDebian apt key
      apt_key:
         id: DD95CC430502E37EF840ACEEA5D32F012649A5A9
         url: http://neuro.debian.net/_static/neuro.debian.net.asc
         state: present

    - name: install NeuroDebian repository
      apt_repository:
        repo: deb http://neuro.debian.net/debian bionic main contrib non-free
        state: present
        update_cache=yes

    - name: import the ros apt key
      apt_key:
         id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
         url: hkp://keyserver.ubuntu.com:80
         state: present

    - name: install ros repository
      apt_repository:
        repo: deb [arch=amd64] http://packages.ros.org/ros/ubuntu bionic main
        state: present
        update_cache=yes

    - name: install base packages
          apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
          with_items:
            - alpine
            - ant
            - apt-clone
            - apt-transport-https
            - atom
            - libarmadillo8
            - libarmadillo-dev
            - bazel
            - bison
            - bsd-mailx
            - build-essential
            - cabal-install
            - cargo
            - clang
            - clang-format
            - cmake
            - cmake-extras
            - code
            - codeblocks
            - cowsay
            - crystal
            - curl
            - cython
            - default-jdk
            - default-jre
            - diceware
            - diceware-doc
            - dosbox
            - doxygen
            - emacs
            - emscripten
            - exfat-fuse
            - exfat-utils
            - expect
            - figlet
            - fish
            - firefox
            - flex
            - fortune-mod
            - fortunes
            - fsharp
            - gcc
            - gcc-8
            - g++-8
            - gcc-multilib
            - geany
            - geary
            - gettext
            - gimp
            - git
            - ghostscript
            - golang
            - google-chrome-stable
            - graphviz
            - gromacs
            - gsfonts-x11
            - guake
            - haskell-platform
            - haskell-platform-doc
            - htop
            - ipython
            - ipython3
            - jupyter-notebook
            - kate
            - keras-doc
            - language-pack-*
            - latexmk
            - libboost-all-dev
            - libcontrolsfx-java
            - libffi-dev
            - libfuse-dev
            - libfuse2
            - libhdf5-dev
            - libjpeg-dev
            - libldap2-dev
            - libncursesw5-dev
            - libosmesa6-dev
            - libreoffice
            - libsasl2-dev
            - libssl-dev
            - libpcre16-3
            - libtiff-tools
            - llvm
            - luarocks
            - maven
            - mercurial
            - mesa-utils
            - mesa-utils-extra
            - mono-complete
            - mutt
            - netbeans
            - nodejs
            - nnn
            - ocaml
            - octave
            - okular
            - opam
            - openjdk-8-jdk
            - openjfx
            - owncloud-client
            - p7zip-full
            - pass
            - pdsh
            - php
            - php-mbstring
            - php-mysql
            - php-xml
            - php-zip
            - pidgin
            - pinta
            - plan
            - plink1.9
            - postgresql-client
            - pypy
            - python
            - python-pip
            - python-pygame
            - python-qt4
            - python-qt4-dev
            - python-qt4-gl
            - python-scipy
            - python-sklearn
            - python-vispy
            - python3
            - python3.7
            - python3-django
            - python3-ipython
            - python3-keras
            - python3-notebook
            - python3-paramiko
            - python3-scipy
            - python3-sklearn
            - python3-theano
            - python3-tk
            - python3-venv
            - qemu
            - r-base
            - re2c
            - ros-melodic-desktop-full
            - ruby
            - scala
            - screen
            - shellcheck
            - singularity-container
            - slack-desktop
            - smlnj
            - spyder
            - spyder3
            - sqlite3
            - sshpass
            - subversion
            - sublime-text
            - swig
            - sysstat
            - tcl
            - tcsh
            - terminator
            - texlive-full
            - texstudio
            - theano-doc
            - thonny
            - tmpreaper
            - tmux
            - ubuntu-desktop
            - ubuntu-minimal
            - ubuntu-restricted-extras
            - ubuntu-standard
            - unrar
            - unzip
            - update-motd
            - valgrind
            - virtualbox
            - vim
            - xfsprogs
            - xterm
            - xvfb
            - xz-utils
            - zlib1g-dev
            - zsh

    - name: remove some packages
          apt: pkg={{item}} state=absent update_cache=yes cache_valid_time=604800
          with_items:
            - eclipse
            - gnome-initial-setup
            - gnome-software
            - transmission-common
            - transmission-gtk
            - ubuntu-software
            - ubuntu-web-launchers
